name: "Build"
on:
  push:
  schedule:
    - cron: "0 8 * * 6"
jobs:
  build:
    name: "Build on JDK ${{ matrix.jdk }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk:
          - 21
    steps:
      - uses: actions/checkout@v4
      - name: "Set up JDK ${{ matrix.jdk }}"
        uses: actions/setup-java@v4
        with:
          java-version: "${{ matrix.jdk }}"
          distribution: "zulu"
      - name: "Build with Gradle"
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          CLOUDFLARE_DOMAIN_NAME: ${{ secrets.CLOUDFLARE_DOMAIN_NAME }}
        run: ./gradlew check distTar
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: "Kotlin Application"
          path: "build/distributions/ddns.tar"
          retention-days: 1
  build-and-push-image:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: "Kotlin Application"
          path: "build/distributions/"
      - name: "Untar files"
        run: mkdir -p build/install && tar -xvf build/distributions/ddns.tar -C $_
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3
      - name: "Login to GHCR"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build and push"
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/heapy/ddns-fullstack:main
